TILE_SIZE = 32

MAP_ROWS = 13
MAP_COLS = 20

MAP_WIDTH = MAP_COLS * TILE_SIZE
MAP_HEIGHT = MAP_ROWS * TILE_SIZE

HUD_WIDTH = 280

SCREEN_WIDTH = MAP_WIDTH + HUD_WIDTH
SCREEN_HEIGHT = MAP_HEIGHT

FPS = 60

TITLE = "iZood: Entregas Algorítmicas"